name: build release, release image to DockerHub
on:
  release:
    types:
      - published
env:
  CONTAINER_RUN_OPTIONS: " "

jobs:
  release-assests:
    name: release kubeedge components
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target:
          - kubeedge
          - edgesite
          - keadm
        os:
          - linux
        arch:
          - amd64
          - arm64
          - arm
        ARM_VERSION:
          - GOARM7
          - GOARM8
          - ""
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          # fetch-depth:
          # 0 indicates all history for all branches and tags.
          # for `git describe --tags` in Makefile.
          fetch-depth: 0
      - name: Making and packaging
        run: |
          docker pull kubeedge/build-tools
          make release ARM_VERSION=${{ matrix.ARM_VERSION }}
      - name: Uploading assets...
        if: ${{ !env.ACT }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            _output/release/${{ github.ref_name }}/${{ matrix.target }}-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
            _output/release/${{ github.ref_name }}/checksum_${{ matrix.target }}-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz.txt

  publish-image-to-dockerhub:
    name: publish to DockerHub
    strategy:
      matrix:
        target:
          - cloudcore
          - admission
          - edgesite-agent
          - edgesite-server
          - csidriver
          - iptablesmanager

    runs-on: ubuntu-18.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: checkout code
        uses: actions/checkout@v2
        with:
          # fetch-depth:
          # 0 indicates all history for all branches and tags.
          # for `git describe --tags` in Makefile.
          fetch-depth: 0
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and publish images
        run: |
          make upload-images
